### ISSUE TITLE
vocab size mismatch error

### ISSUE THREAD

**Issue by gihanpanapitiya** [cambridge-mlg/weighted-retraining#8] opened 2023-12-04 23:39 UTC
I am getting a vocab size mismatch error. Looks like the vocab size used in the pretrained model is different than the vocabulary size corresponding to the data provided in the repository. Is this the case?

**Comment by AustinT** [comment] 2023-12-05 10:06
Thanks for your interest in our code. The vocab size should be the same: we ran everything before publishing this repo so I don't think there should be a size mismatch.

If you are still having problems, can you provide a minimal example of something not working?

**Comment by gihanpanapitiya** [comment] 2023-12-06 23:58
I am trying to run the below optimization.

```
# Meta flags
gpu="--gpu"  # change to "" if no GPU is to be used
seed_array=( 1 2 3 4 5 )
root_dir="logs/opt/chem"
start_model="assets/pretrained_models/chem.ckpt"
query_budget=500
n_retrain_epochs=0.1
n_init_retrain_epochs=1

# Experiment 1: weighted retraining with different parameters
# ==================================================
k_high="1e-1"
k_low="1e-3"
r_high=100
r_low=50
r_inf="1000000"  # Set to essentially be infinite (since "inf" is not supported)
weight_type="rank"
lso_strategy="opt"

# Set specific experiments to do:
# normal LSO, our setting, retrain only, weight only, high weight/low retrain, high retrain/low weight
k_expt=(  "inf"    "$k_low" "inf"    "$k_low" "$k_low"  "$k_high" )
r_expt=(  "$r_inf" "$r_low" "$r_low" "$r_inf" "$r_high" "$r_low" )

expt_index=0  # Track experiments
for seed in "${seed_array[@]}"; do
    for ((i=0;i<${#k_expt[@]};++i)); do

        # Increment experiment index
        expt_index=$((expt_index+1))

        # Break loop if using slurm and it's not the right task
        if [[ -n "${SLURM_ARRAY_TASK_ID}" ]] && [[ "${SLURM_ARRAY_TASK_ID}" != "$expt_index" ]]
        then
            continue
        fi


        # Echo info of task to be executed
        r="${r_expt[$i]}"
        k="${k_expt[$i]}"
        echo "r=${r} k=${k} seed=${seed}"

        # Run command
        python weighted_retraining/opt_scripts/opt_chem.py \
            --seed="$seed" $gpu \
            --query_budget="$query_budget" \
            --retraining_frequency="$r" \
            --result_root="${root_dir}/${weight_type}/k_${k}/r_${r}/seed${seed}" \
            --pretrained_model_file="$start_model" \
            --lso_strategy="$lso_strategy" \
            --train_path=data/chem/zinc/orig_model/tensors_train \
            --val_path=data/chem/zinc/orig_model/tensors_val \
            --vocab_file=data/chem/zinc/orig_model/vocab.txt \
            --property_file=data/chem/zinc/orig_model/pen_logP_all.pkl \
            --n_retrain_epochs="$n_retrain_epochs" \
            --n_init_retrain_epochs="$n_init_retrain_epochs" \
            --n_best_points=2000 --n_rand_points=8000 \
            --n_inducing_points=500 \
            --weight_type="$weight_type" --rank_weight_k="$k"

    done
done
```

I am getting this error,


```
KeyError: Caught KeyError in DataLoader worker process 0. 

Original Traceback (most recent call last): 

  File "/../../../../../lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop 

    data = fetcher.fetch(index) 

  File "/../../../../../lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch 

    data = [self.dataset[idx] for idx in possibly_batched_index] 

  File "/../../../../../lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp> 

    data = [self.dataset[idx] for idx in possibly_batched_index] 

  File "/model/dir/weighted_retraining/chem/jtnn/datautils.py", line 170, in __getitem__ 

    return tensorize(self.data[idx], self.vocab, assm=self.assm) 

  File "/model/dir/weighted_retraining/chem/jtnn/datautils.py", line 174, in tensorize 

    set_batch_nodeID(tree_batch, vocab) 

  File "/model/dir/weighted_retraining/chem/jtnn/datautils.py", line 204, in set_batch_nodeID 

    node.wid = vocab.get_index(node.smiles) 

  File "/ model/dir/weighted_retraining/chem/jtnn/vocab.py", line 21, in get_index 

    return self.vmap[smiles] 

KeyError: 'C1=CNN=C1' 
```

**Comment by AustinT** [comment] 2023-12-08 14:11
@gihanpanapitiya I am running this now. So far no errors, but it takes a long time to run. Do you know which setting of r,k in the loop caused the error?

My guess is that you (by chance) find a molecule which is not encodable by the JTNN encoder. This is just a property of JTNNs and is not something really fixable. Do you get this error repeatedly or just once?

**Comment by gihanpanapitiya** [comment] 2023-12-11 16:54
@AustinT I ran this again using `k_expt=( "$k_high" )` and `r_expt=( "$r_low" )`. And got the same error.
`k_high="1e-1"`
`r_low=50`

**Comment by AustinT** [comment] 2023-12-12 15:41
> @AustinT I ran this again using `k_expt=( "$k_high" )` and `r_expt=( "$r_low" )`. And got the same error. `k_high="1e-1"` `r_low=50`

Thank you very much. I just re-ran it and got no errors, but I do recall receiving an error like this before. I think the issue is that the JTNN cannot encode every single molecule. The occurrence of such molecules is random and probably occurs on your machine but not mine. You could probably fix this by adding a try/except clause somewhere. Alternatively, try a different random seed.

However, to keep this code consistent with the original paper I won't merge this into the main branch. I will close this issue and mark as "wontfix". If you want to use this code for anything though I can try to help, feel free to send me an email.

**Closed as completed by AustinT** 2023-12-12 15:41 UTC
Labels: wontfix
